### ISSUE TITLE
Disguising pointer as usize to leak back to Elixir?

### ISSUE THREAD

**Issue by naps62** [naps62/imageflow_ex#2]
i needed a way to send a pointer to the job back to Elixir. Both for reference, and for later being able to clean up memory

I'm also constrained by [rustler](https://github.com/rusterlium/rustler), which includes logic to automatically encode values as Elixir terms when calling Rust NIF functions. It doesn't implement an encoder for any kind pointer or box type (which makes perfect sense)

So my current approach is to cast the pointer as a `usize` and send that over. It also ends up serving as a unique identifier on the job on the Elixir side of things

Is there a better approach here?

**Comment by naps62** [comment]
cc/ @lilith

**Comment by lilith** [comment]
I think that's fine for the low-level bindings API. I would suggest wrapping it in a higher level object that contains the pointer and wraps the methods accordingly. And I would suggest not using the JSON API directly, but wrapping it in a graph-generation API, as it's hard to work with directly.

**Comment by naps62** [comment]
Not sure what you mean regarding that graph-generation API? Could you point me to an example?

**Comment by lilith** [comment]
Sure. [Imageflow.NET](https://github.com/imazen/imageflow-dotnet) (our highest-quality set of bindings) allows for generating a graph with fluent function calls. 

We do this with a class that builds a linked-graph of nodes with unique IDs.

Users start with an [ImageJob](https://github.com/imazen/imageflow-dotnet/blob/54f4cb48f65125743e41f4bad77c605f7bf4b4e6/src/Imageflow/Fluent/ImageJob.cs) instance, on which they can call Decode() or CreateCanvas() to create a starting point. This in turn returns a [BuildNode](https://github.com/imazen/imageflow-dotnet/blob/54f4cb48f65125743e41f4bad77c605f7bf4b4e6/src/Imageflow/Fluent/BuildNode.cs) instance which allows for a wide range of operation functions to be called. Each [node has a unique ID](https://github.com/imazen/imageflow-dotnet/blob/54f4cb48f65125743e41f4bad77c605f7bf4b4e6/src/Imageflow/Fluent/BuildItemBase.cs) These all return BuildNode instances except for Encode(), which returns a [BuildEndpoint](https://github.com/imazen/imageflow-dotnet/blob/main/src/Imageflow/Fluent/BuildEndpoint.cs) on which you can only call .Finish(). 

.Finish() adds the decode and encode IO stuff to the Context and generates the JSON. https://github.com/imazen/imageflow-dotnet/blob/54f4cb48f65125743e41f4bad77c605f7bf4b4e6/src/Imageflow/Fluent/ImageJob.cs#L184-L222

The edges and nodes are created from the structure [like this](https://github.com/imazen/imageflow-dotnet/blob/54f4cb48f65125743e41f4bad77c605f7bf4b4e6/src/Imageflow/Fluent/ImageJob.cs#L442-L516).

I like this approach because it prevents a large range of mistakes and generally if it compiles it's a well-formed JSON job. 

You can see usage examples in the readme: https://github.com/imazen/imageflow-dotnet

**Comment by naps62** [comment]
FYI @lilith I started work on the graph API on a branch. the graph part itself is actually done already, I just need to add the different operation functions

```elixir
    Graph.new()
    |> Graph.decode_file(@input_path)
    |> Graph.branch(fn graph ->
      graph
      |> Graph.constrain(20, nil)
      |> Graph.encode_to_file("/tmp/20x20.png")
    end)
    |> Graph.branch(fn graph ->
      graph
      |> Graph.constrain(nil, 10)
      |> Graph.encode_to_file("/tmp/10x10.png")
    end)
    |> Graph.run()

```

**Comment by lilith** [comment]
Awesome!

**Comment by naps62** [comment]
this is now done, with a couple of features missing, but the main bulk is here already. I don't imagine those features will be the main workflow of most people using this, so I'm considering this ready
